version: "3"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile_backend
    volumes:
      - .:/var/www/server
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    env_file: .env
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
  frontend:
    build:
      context: .
      dockerfile: dockerfile_frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - "3000:3000"
