FROM python:3.8

WORKDIR /var/www/server

COPY adverity ./adverity
COPY star_wars ./star_wars
COPY csv_files ./csv_files
COPY manage.py ./
COPY requirements.txt ./
COPY run.sh ./

RUN pip install -r requirements.txt

RUN chmod +x run.sh
CMD ["bash", "run.sh"]